version: '3.8'

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - "todo_frontend"
      - "todo_backend"
    container_name: reverse-proxy

  todo_frontend:
    image: todo_frontend_dev
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./todo-frontend/:/usr/src/app
    environment:
      - REACT_APP_BACKEND_URL=api/

  todo_backend:
    image: todo_backend_dev
    build:
      context: ./todo-backend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    ports:
      - 3001:3001
    volumes:
      - ./todo-backend/:/usr/src/app
    depends_on:
      - "mongo"
      - "redis"
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  
  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
